### ISSUE TITLE
Random Mouse Action

### ISSUE THREAD

**Issue by tantinevincent** [tantinevincent/Onegai-ooyodosan#29]
Random Click Location:
- [x] Docking
- [x] Fight
- [x] Expedition
- [x] Quest
- [x] Resupply
- [x] Dismantling

**Comment by hSATAC** [comment]
checkbox.png is missing in random_action branch...
Thanks :+1:

**Comment by tantinevincent** [comment]
Oops, I forgot that. Thanks for your report, @hSATAC!
