### ISSUE TITLE
Resupply broken (Saury Fish update)

### ISSUE THREAD

**Issue by vSwifty** [tantinevincent/Onegai-ooyodosan#34]
With the new addition of resupply all ships in fleet over the select all ships checkbox in resupply menu resupply function is looping.

It just has to be tweaked to click on the new box.

new checkbox
![new checkbox](http://i.imgur.com/xJVVp5C.png)
new resupply all button
![new resupply all button](http://i.imgur.com/8Wd9UVn.png)

**Comment by vSwifty** [comment]
Found a fix


Open up resupply_runner
and delete lines 37-47
replace resupply_everything with the new checkbox
reduce sleep to 1 or 2

**Comment by tantinevincent** [comment]
Thanks your report, I will fix this ASAP.
